### PR TITLE
Customizable notification email mailable

### PR DESCRIPTION
**Pull request by CodeWithDennis**
Since the email is sent through a notification, we couldn’t customize it when trying to publish the view because there wasn't one. I’ve added a new view for the email with a default layout (see screenshot). Let me know your thoughts or if you have any feedback.

**Since the Blade view is a markdown file, we shouldn't format it, as that could cause it to break.**

_TLDR: Package users can now override the view_

Scherm­afbeelding 2024-08-23 om 11 11 01

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
Perhaps adding the option in the config to override the subject? Or, if you want to take it a step further, create a custom mailable class.

**Comment by Baspa** [comment]
> Perhaps adding the option in the config to override the subject? Or, if you want to take it a step further, create a custom mailable class.

Nice PR! Creating a custom mailable class would be the nicest solution imo. Can you take a look at it, or do you want me to try? @CodeWithDennis

**Comment by CodeWithDennis** [comment]
> > Perhaps adding the option in the config to override the subject? Or, if you want to take it a step further, create a custom mailable class.
> 
> Nice PR! Creating a custom mailable class would be the nicest solution imo. Can you take a look at it, or do you want me to try? @CodeWithDennis

I will take a look, i will let you know if i can pull it off today.

**Comment by CodeWithDennis** [comment]
@Baspa I'm not entirely sure if this will work because the Notification is supposed to return a `MailMessage`. Moving it to the config would also mean you'd need to bring over the `getTwoFactorCode` method.

**Comment by Baspa** [comment]
Hmm according to the documentation it should be possible: https://laravel.com/docs/11.x/notifications#using-mailables 

> If needed, you may return a full [mailable object](https://laravel.com/docs/11.x/mail) from your notification's toMail method. When returning a Mailable instead of a MailMessage, you will need to specify the message recipient using the mailable object's to method:

@CodeWithDennis

**Comment by CodeWithDennis** [comment]
> Hmm according to the documentation it should be possible: https://laravel.com/docs/11.x/notifications#using-mailables
> 
> > If needed, you may return a full [mailable object](https://laravel.com/docs/11.x/mail) from your notification's toMail method. When returning a Mailable instead of a MailMessage, you will need to specify the message recipient using the mailable object's to method:
> 
> I'm going to think about the `getTwoFactorCode` part. @CodeWithDennis

Oh nice find, i will refactor it.

**Comment by Baspa** [comment]
Maybe the user should make sure their mailable can accept the two factor code as argument? Then we could do something like this:

```php
    public function toMail(object $notifiable): Mailable
    {
        $mailable = config('filament-two-factor-auth.mail_mailable') ?? SendTwoFactor::class;

        $mail = new $mailable($this->getTwoFactorCode($notifiable));

        $mail->to($notifiable->email);

        return $mail
     }
```

**Comment by CodeWithDennis** [comment]
> Maybe the user should make sure their mailable can accept the two factor code as argument? Then we could do something like this:
> 
> ```
>     public function toMail(object $notifiable): Mailable
>     {
>         $mailable = config('filament-two-factor-auth.mail_mailable') ?? SendTwoFactor::class;
> 
>         $mail = new $mailable($this->getTwoFactorCode($notifiable));
> 
>         $mail->to($notifiable->email);
> 
>         return $mail
>      }
> ```

That might work... The changes have been pushed. @Baspa

**Comment by Baspa** [comment]
Great! Code is looking good, thank you for your effort. I will merge it @CodeWithDennis

**Comment by CodeWithDennis** [comment]
> Great! Code is looking good, thank you for your effort. I will merge it @CodeWithDennis

Thanks! Maybe you could bring up the option to customize the email as a discussion or issue for a future feature. I can see that some people might want more control, even though they can already change the view.

**Pull request merged**
